apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      repo_plugins:
        ci-bot:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
    
        openeuler:
        - openeuler-ipb
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        - robot-gitee-openeuler-cla
        - robot-gitee-openeuler-tech4dx-label
        - datastat-server
    
        src-openeuler:
        - openeuler-ipb
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        - robot-gitee-openeuler-cla
        - robot-gitee-openeuler-tech4dx-label
        - datastat-server
    
        openeuler-competition:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        - robot-gitee-openeuler-cla
        - datastat-server
    
        openeuler-compliance:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        - robot-gitee-openeuler-cla
        - datastat-server
    
        openeuler-risc-v:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        - robot-gitee-openeuler-cla
        - datastat-server
    
        openeuler-practice-courses:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        - robot-gitee-openeuler-cla
        - datastat-server
    
        openeuler-customization:
        - robot-gitee-openeuler-label
        - robot-gitee-openeuler-lifecycle 
        - robot-gitee-openeuler-assign-issue
        - robot-gitee-openeuler-openeuler-review
        - robot-gitee-openeuler-openeuler-welcome
        - robot-gitee-openeuler-cla
        - datastat-server

      plugins:
      - name: robot-gitee-openeuler-lifecycle
        endpoint: http://service-lifecycle.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: robot-gitee-openeuler-assign-issue
        endpoint: http://service-assign-issue.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
      - name: robot-gitee-openeuler-label
        endpoint: http://service-label.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: robot-gitee-openeuler-openeuler-welcome
        endpoint: http://service-openeuler-welcome.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Issue Hook"
        - "Merge Request Hook"
      - name: robot-gitee-openeuler-openeuler-review
        endpoint: http://service-openeuler-review.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: robot-gitee-openeuler-cla
        endpoint: http://service-cla.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Merge Request Hook"
        - "Note Hook"
      - name: openeuler-ipb
        endpoint: http://openeuler-ipb-service.openeuler-ipb.svc.cluster.local/hooks
        events:
        - "Merge Request Hook"
        - "Note Hook"
        - "Issue Hook"
      - name: robot-gitee-openeuler-tech4dx-label
        endpoint: http://service-tech4dx-label.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Issue Hook"
        - "Note Hook"
      - name: robot-gitee-openeuler-hook-delivery
        endpoint: http://service-hook-delivery.robot-gitee-openeuler.svc.cluster.local:8888/gitee-hook
        events:
        - "Note Hook"
        - "Issue Hook"
        - "Merge Request Hook"
        - "Push Hook"
      - name: datastat-server
        endpoint: http://om-service.robot-gitee-om.svc.cluster.local:8888/query/gitee/webhook
        events:
        - "Issue Hook"
        - "Merge Request Hook"
        - "Note Hook"
