apiVersion: v1
kind: ConfigMap
metadata:
  name: py-configmap
  namespace: xihe-new
data:
  config.yaml: |
    mq:
      address: "${KAFKA_ADDRESS}"
      topics:
        submission: "xihe_submission_new"
    endpoint: "service-internal-server.xihe-new.svc.cluster.local:8888"
    matchs:
      - competition_id: "2"
        answer_final_path: "competition/2/final/result/label-final-public.txt"
        answer_preliminary_path: "competition/2/preliminary/result/label.txt"
        pos: 1
        cls: 5
        prefix: "competition"
      - competition_id: "3"
        answer_final_path: "competition/3/final/result/label-final-public.txt"
        answer_preliminary_path: "competition/3/preliminary/result/label.txt"
        pos: 1
        cls: 256
        prefix: "competition"
      - competition_id: "1"
        fid_weights_final_path: "competition/1/final/result/pt_inception-2015-12-05-6726825d.pth"
        fid_weights_preliminary_path: "competition/1/preliminary/result/pt_inception-2015-12-05-6726825d.pth"
        real_final_path: "competition/1/final/result/target_style_vangogh"
        real_preliminary_path: "competition/1/preliminary/result/target_style_vangogh"
        prefix: "competition"
      - competition_id: "learn23-text"
        answer_preliminary_path: "competition/learn23-text/preliminary/label.txt"
        pos: 0
        cls: 6
        prefix: "competition"
      - competition_id: "learn23-img"
        answer_preliminary_path: "competition/learn23-img/preliminary/label.txt"
        pos: 0
        cls: 4
        prefix: "competition"
