apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    topic: robot-gitee-openlookeng
    user_agent: robot-gitee-openlookeng
    kafka:
      address: "${KAFKA_ADDRESS}"
