apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- lifecycle
- welcome
- label
- assign-issue
- opengauss-review
- repo-watcher
- associate
- cla
- opengauss-sigguide
- hook-dispatcher
- hook-delivery
- access
commonLabels:
  app: infrastructure-robot-gitee
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-gitee-opengauss
